### ISSUE TITLE
Jobs fail routing when routing a spawned request to a child garden

### ISSUE THREAD

**Issue by Jake-Ross** [beer-garden/beer-garden#1157]
It looks as if setting up a job for a child garden in a particular way will make the garden try to route operation models instead of requests, which have no saving schema for mongo (?). This should be looked into more.

## To reproduce
- Set up a parent/child garden relationship
- Schedule a job in the *parent's* UI, to execute on a *child* system
- Instead of executing, the garden will error, which is not really cool of it to do

Traceback should look like this:
```python
[MainProcess] - beer_garden.scheduler - ERROR - Error executing awd: 616703c2c29ae2cc3c2c21a3: 'super' object has no attribute 'save'
Traceback (most recent call last):                                                             
  File "/home/brewmeister/beer-garden/app/beer_garden/scheduler.py", line 483, in run_job
    kwargs={"wait_event": wait_event},                                                                             
  File "/home/brewmeister/beer-garden/app/beer_garden/router.py", line 185, in route
    return initiate_forward(operation)
  File "/home/brewmeister/beer-garden/app/beer_garden/router.py", line 235, in initiate_forward
    operation = _pre_forward(operation)                                                                              
  File "/home/brewmeister/beer-garden/app/beer_garden/router.py", line 499, in _pre_forward
    operation.model = db.create(operation.model)
  File "/home/brewmeister/beer-garden/app/beer_garden/db/mongo/api.py", line 351, in create                         
    mongo_obj.save(force_insert=True)                        
  File "/home/brewmeister/beer-garden/app/beer_garden/db/mongo/models.py", line 98, in save                                                                                                                 
    return super().save(*args, **kwargs)                                      
AttributeError: 'super' object has no attribute 'save'
```

**Comment by scott-taubman** [comment]
The problem here is that the job scheduler [tries to route a `RequestTemplate`](https://github.com/beer-garden/beer-garden/blob/develop/src/app/beer_garden/scheduler.py#L478) rather than a `Request`.  `RequestTemplate` is not a standalone `Document` class and can't be saved.

When the job is executed for the local garden, an actual `Request` is [created from the template](https://github.com/beer-garden/beer-garden/blob/develop/src/app/beer_garden/requests.py#L598). No such thing happens in the code path for jobs that need to be forwarded to child gardens.

Ultimately it's not clear to me why the job scheduler wants to create a `RequestTemplate` to begin with rather than proper `Request`.  I'd probably start by evaluating that and seeing if we can just fix this problem close to the source.
