### ISSUE TITLE
Remove pymongo dependencies

### ISSUE THREAD

**Issue by catattack05** [beer-garden/beer-garden#1329]
Remove pymongo from examples like:

https://github.com/beer-garden/beer-garden/blob/develop/src/app/beer_garden/db/mongo/api.py#L17

Specifically, places where we are importing pymongo errors where really we should be importing mongoengine errors.

Additionally, there are instances where we import from `bson`, which is actually provided by pymongo.  We should look to eliminate those instances as well.  Specifically:

* Anywhere that we're doing something like:
  ```python
  from bson import ObjectId
  ...
  thing = ObjectId(mystrid)
  ```
  We should instead by doing:
  ```python
  from mongoengine.fields import ObjectIdField
  ...
  thing = ObjectIdField().to_mongo(mystrid)
  ```
* There is a single usage of `from bson import DBRef`. The [place where that is used](https://github.com/beer-garden/beer-garden/blob/develop/src/app/beer_garden/db/mongo/util.py#L128) is a migration that's fixing an issue from a very specific, fairly old version of beer-garden.  I think it is safe to remove that whole `_ensure_owner_collection_migration()` function at this point, as the likelihood that anyone is specifically running beer-garden >3.0.0, <3.2.0, seems sufficiently small.  We can put a warning in the release notes if we care to.

**Comment by aks14075032** [comment]
@catattack05 I want to work on this issue but I'm facing problem while setting up the project. 

```
(base) apli.ai@192 app % python bin/app.py -c example_configs/config.yaml
2022-06-04 15:57:56,128 - beer_garden.__main__ - INFO - Hi! Please give me just a minute to get set up.
2022-06-04 15:57:56,209 - beer_garden.db.mongo.util - INFO - auth.role_definition_file not defined. No roles will be synced.
2022-06-04 15:57:56,295 - beer_garden.app - INFO - All set! Let me know if you need anything else!
2022-06-04 15:57:56,583 - beer_garden.api.stomp - INFO - Stomp entry point started
2022-06-04 15:57:56,702 - beer_garden.api.http - INFO - Http entry point started
2022-06-04 15:57:56,703 - beer_garden.local_plugins.manager - ERROR - Error scanning plugin path: [Errno 2] No such file or directory: 'plugins'
Traceback (most recent call last):
  File "/Users/apli.ai/Desktop/Personal/Open_Source/beer-garden/src/app/beer_garden/local_plugins/manager.py", line 409, in scan_path
    for path in plugin_paths:
  File "/Users/apli.ai/.pyenv/versions/3.7.13/lib/python3.7/pathlib.py", line 1107, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'plugins'
```
Any help will be appreciated 
Using -- MacOS with M1 Chip

**Comment by aks14075032** [comment]
@catattack05 Any help with above issue ?

**Comment by scott-taubman** [comment]
> @catattack05 Any help with above issue ?

@aks14075032 We appreciate your interest in the project and helping with this issue, but we're not really really in a good spot to accept outside contributions at this time.  This particular issue is already being worked by a member of the core team and there aren't really any remaining open issues that we're looking to pursue any time soon.
