### ISSUE TITLE
brew-view has issues with MongDB

### ISSUE THREAD

**Issue by kylecribbs** [beer-garden/beer-garden#198]
I did a git clone of the repo and docker-compose up  on the docker-compose.yml. I noticed that the brew view didn't start (cant browse to it) so i did a docker logs docker-compose_brew-view_1, which displayed:
```python
2018-11-08 06:27:43,784 - tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7ff17c35a0d0>, <Future finished exception=NotUniqueError('Tried to save duplicate unique keys (E11000 duplicate key error collection: beer_garden.role index: unique_index dup key: { : "bg-readonly" })',)>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mongoengine/document.py", line 378, in save
    object_id = self._save_create(doc, force_insert, write_concern)
  File "/usr/local/lib/python3.6/site-packages/mongoengine/document.py", line 434, in _save_create
    object_id = collection.save(doc, **write_concern)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 3137, in save
    to_save, True, check_keys, manipulate, write_concern)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 607, in _insert
    bypass_doc_val, session)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 595, in _insert_one
    acknowledged, _insert_command, session)
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1243, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1196, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 592, in _insert_command
    _check_write_command_response(result)
  File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 217, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 198, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: beer_garden.role index: unique_index dup key: { : "bg-readonly" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 779, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/brew_view/__init__.py", line 87, in startup
    'Unable to connect to mongo, is it started?'
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.6/site-packages/brew_view/__init__.py", line 150, in _progressive_backoff
    while not func():
  File "/usr/local/lib/python3.6/site-packages/bg_utils/__init__.py", line 304, in setup_database
    _verify_db()
  File "/usr/local/lib/python3.6/site-packages/bg_utils/__init__.py", line 563, in _verify_db
    _ensure_roles()
  File "/usr/local/lib/python3.6/site-packages/bg_utils/__init__.py", line 377, in _ensure_roles
    'bg-system-read',
  File "/usr/local/lib/python3.6/site-packages/mongoengine/document.py", line 401, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: beer_garden.role index: unique_index dup key: { : "bg-readonly" })
```

**Comment by kylecribbs** [comment]
I fixed by making MongoDB have a persistent storage to a specified location. 
Created a folder in docker/docker-compose/ called mongo-data and mongo-config
changed docker-compose to have 
- ./mongo-data:/data/db
- ./mongo-config:/data/configdb

**Comment by loganasherjones** [comment]
Hello! First, thanks so much for the contribution!

This is an interesting little error. I think this is actually a race condition when bartender and brew-view are started at the same time for the first time. Neither think this index has been created yet, and so they both try to create it. One of them will certainly fail. 

I believe restarting brew-view would have solved this issue (`docker-compose restart brew-view`) If you tried that and it didn't work, then I might be wrong, and I'd like to see the error after restart (if the one above is not it).

@hazmat345 thoughts?

**Comment by hazmat345** [comment]
Hmm. I thought we fixed that by having bartender verify the brew-view connection before attempting to do anything with mongo.

I'm wondering if changes to the brew-view startup are causing the web portion to come online before it's really ready. I'll take a look.

**Comment by hazmat345** [comment]
I'm pretty stumped. Here's what we're doing:
```python
if Role.objects.count() == 0:
    logger.warning('No roles found: creating convenience roles')

    logger.warning('About to create bg-readonly role')
    Role(
        name='bg-readonly',
        description='Allows only standard read actions',
        permissions=[
            'bg-command-read',
            'bg-event-read',
            'bg-instance-read',
            'bg-job-read',
            'bg-queue-read',
            'bg-request-read',
            'bg-system-read',
        ]
    ).save()
```
So there's absolutely the potential for that race to exist, but nothing I've tried seems to put things into a state where we'd encounter it. The only thing I can think of is maybe if multiple brew-view containers were started at the same time?

We can definitely do a better job of retrying / failing more gracefully if we hit this condition, though. Especially for the roles that are just nice-to-haves, not mandatory.

We could also have bartender just check for mongo connectivity and not verify correctness. That would also get us closer to the point where bartender doesn't need to exist.

**Comment by loganasherjones** [comment]
Hi @kylecribbs can you tell us what version of software you were running?

**Comment by kylecribbs** [comment]
I think you are right about the race condition. I removed the mongo volumes
```bash
docker volume rm docker-compose_mongo-data
ocker volume rm docker-compose_mongo-config
```
then did a docker-compose up again and it worked. 

Here is the version of my qnap
```bash
[/share/Container/beer-garden/docker/docker-compose] # cat /etc/os-release                         
NAME="QTS"
VERSION="4.3.5 (20181013)"
ID=qts
PRETTY_NAME="QTS 4.3.5 (20181013)"
VERSION_ID="4.3.5"
```

Here is the version of docker
```bash
[/share/Container/beer-garden/docker/docker-compose] # docker --version
Docker version 17.09.1-ce, build a9fd393
```

Let me know if you need anything else.

**Comment by loganasherjones** [comment]
Thanks for the information, sorry I wasn't clear. Can you tell me the version of brew-view and bartender that you are running?

**Comment by kylecribbs** [comment]
It should be the most recent git clone.
In the "About" of Beer-Garden it states:

Component Name | Version
-- | --
Bartender | 2.4.0
Brew View | 2.4.6
Current API | v1
Supported API Versions | v1

**Comment by hazmat345** [comment]
Hi @kylecribbs - I just merged a change that should help with handling this case a little more gracefully. I'm still not exactly sure how this happened in the first place though, so please let us know if you see this again. Thanks!
