### ISSUE TITLE
Decorated Commands

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#281]
I'm not sure what would happen if someone tried to use a real decorator on a `@command` method. We should see if that's possible.

**Comment by hazmat345** [comment]
It looks like `@classmethod` and `@staticmethod` fail on Python 3.6. Going to use the issue to add support for that, which makes this not a good first issue anymore.

**Comment by TheBurchLog** [comment]
Tested with client: 
```python
class TestClient:
    
    @staticmethod
    @command
    def static_method_first():
        return "static_method_first"
    
    
    @command
    @staticmethod
    def static_method_second():
        return "static_method_second"
    
    @classmethod
    @command
    def class_method_first(cls):
        return "class_method_first"
    
    
    @command
    @classmethod
    def class_method_second(cls):
        return "class_method_second"
```

Everything works except for `class_method_second`. It returns a error message of:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/beer-garden/src/app/plugins/test/test/__main__.py", line 7, in <module>
    class ChildClient:
  File "/beer-garden/src/app/plugins/test/test/__main__.py", line 38, in TestClient
    def class_method_second(cls):
  File "/beer-garden/src/app/src/brewtils/brewtils/decorators.py", line 210, in command
    if str(inspect.signature(_wrapped)._return_annotation) in [
  File "/usr/lib/python3.10/inspect.py", line 3254, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
  File "/usr/lib/python3.10/inspect.py", line 3002, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib/python3.10/inspect.py", line 2396, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: <classmethod(<function ChildClient.class_method_second at 0x74d337a48940>)> is not a callable object
```
