### ISSUE TITLE
v3 Shutdown bug

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#388]
Beer Garden gets stuck shutting down. Steps to reproduce:

1. DO NOT run mongo
2. `python ./bin/app.py -c example_config/config.yaml`
3. `Ctrl-C`

I get something like this:

```
2019-12-31 10:59:18,534 - beer_garden.app - INFO - Setting up Event Manager
2019-12-31 10:59:18,545 - beer_garden - INFO - Hi! Please give me just a minute to get set up.
2019-12-31 10:59:19,551 - beer_garden.app - WARNING - Unable to connect to mongo, is it started?
2019-12-31 10:59:19,552 - beer_garden.app - WARNING - Waiting 0.1 seconds before next attempt
2019-12-31 10:59:21,056 - beer_garden.app - WARNING - Unable to connect to mongo, is it started?
2019-12-31 10:59:21,056 - beer_garden.app - WARNING - Waiting 0.2 seconds before next attempt
^C2019-12-31 10:59:21,479 - beer_garden - INFO - Last call! Looks like we gotta close up.
2019-12-31 10:59:22,560 - beer_garden.app - WARNING - Unable to connect to mongo, is it started?
2019-12-31 10:59:22,561 - beer_garden.app - WARNING - Waiting 0.4 seconds before next attempt
^C2019-12-31 10:59:31,062 - beer_garden - INFO - Last call! Looks like we gotta close up.
^C^C^C^CException in thread Application:
Traceback (most recent call last):
  File "/home/logan/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/logan/workspace/bg/beer-garden/src/app/beer_garden/app.py", line 111, in run
    self._startup()
  File "/home/logan/workspace/bg/beer-garden/src/app/beer_garden/app.py", line 134, in _startup
    self._setup_database()
  File "/home/logan/workspace/bg/beer-garden/src/app/beer_garden/app.py", line 223, in _setup_database
    db.initial_setup(beer_garden.config.get("auth.guest_login_enabled"))
  File "/home/logan/workspace/bg/beer-garden/src/app/beer_garden/db/mongo/api.py", line 140, in initial_setup
    check_indexes(doc)
  File "/home/logan/workspace/bg/beer-garden/src/app/beer_garden/db/mongo/util.py", line 188, in check_indexes
    existing = document_class._get_collection().index_information()
  File "/home/logan/.pyenv/versions/beer-garden/lib/python3.7/site-packages/pymongo/collection.py", line 2236, in index_information
    cursor = self.list_indexes(session=session)
  File "/home/logan/.pyenv/versions/beer-garden/lib/python3.7/site-packages/pymongo/collection.py", line 2208, in list_indexes
    _cmd, read_pref, session)
  File "/home/logan/.pyenv/versions/beer-garden/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1455, in _retryable_read
    read_pref, session, address=address)
  File "/home/logan/.pyenv/versions/beer-garden/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1254, in _select_server
    server = topology.select_server(server_selector)
  File "/home/logan/.pyenv/versions/beer-garden/lib/python3.7/site-packages/pymongo/topology.py", line 231, in select_server
    address))
  File "/home/logan/.pyenv/versions/beer-garden/lib/python3.7/site-packages/pymongo/topology.py", line 189, in select_servers
    selector, server_timeout, address)
  File "/home/logan/.pyenv/versions/beer-garden/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

2019-12-31 10:59:52,647 - beer_garden - INFO - Last call! Looks like we gotta close up.
2019-12-31 10:59:52,647 - beer_garden - INFO - OK, we're all shut down. Have a good night!
2019-12-31 10:59:52,647 - beer_garden - INFO - OK, we're all shut down. Have a good night!
2019-12-31 10:59:52,647 - beer_garden - INFO - OK, we're all shut down. Have a good night!
2019-12-31 10:59:52,647 - beer_garden - INFO - Don't forget to drive safe!
```

But the process is still hung. Here is my `ps`:

```
logan    12840 12209  5 10:59 pts/1    00:00:02 /home/logan/.pyenv/versions/beer-garden/bin/python ./bin/app.py -c example_configs/config.yaml
logan    12888 12840  0 10:59 pts/1    00:00:00 /home/logan/.pyenv/versions/beer-garden/bin/python -c from multiprocessing.semaphore_tracker import main;main(8)
```

**Comment by loganasherjones** [comment]
When I kill the process I also get:

```
python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown                           
  len(cache))
```
