### ISSUE TITLE
generate_bartender_config error

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#774]
When installing v2 rpm `generate_bartender_config` fails with a yaml error. Looks like this is happening in 2.4.9 and 2.4.8 but not in 2.4.7. Also doesn't look like this is happening with `generate_brew_view_config`. 

Error:

> Traceback (most recent call last):
  File "/usr/local/bin/generate_bartender_config", line 8, in <module>
    sys.exit(generate_config())
  File "/usr/local/lib/python3.6/site-packages/bartender/__main__.py", line 39, in generate_config
    bg_utils.generate_config_file(spec, sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/bg_utils/__init__.py", line 108, in generate_config_file
    file_type=_get_config_type(config),
  File "/usr/local/lib/python3.6/site-packages/yapconf/__init__.py", line 143, in dump_data
    _dump(data, sys.stdout, file_type, **dump_kwargs)
  File "/usr/local/lib/python3.6/site-packages/yapconf/__init__.py", line 169, in _dump
    yaml.safe_dump(data, stream, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/main.py", line 1255, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/main.py", line 1176, in dump_all
    dumper._representer.represent(data)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 84, in represent
    node = self.represent_data(data)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 111, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 359, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 222, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 111, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 359, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 222, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 111, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 359, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 222, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 121, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/representer.py", line 392, in represent_undefined
    raise RepresenterError('cannot represent an object: %s' % (data,))
ruamel.yaml.representer.RepresenterError: cannot represent an object: []

**Comment by hazmat345** [comment]
Looks like this is being caused by the default value for the new `host_env_vars` config option being set to `[]`.
